version: '3'

services:
  elasticsearch:
    image: docker.pkg.github.com/bong-a/elasticsearch-study/elasticsearch:0.0.1
    volumes:
    - $PWD/config:/usr/share/elasticsearch/config
    - $PWD/repo:/usr/share/elasticsearch/repo # snapshot repo
    environment:
    - discovery.type=single-node
    ports:
    - "9300:9300"
    - "9200:9200"
  kibana:
    image: kibana:6.8.6
    ports:
    - "5601:5601"
    depends_on: 
    - "elasticsearch"
networks:
  default:
    external:
      name: es-network